name: Pull Request Checks
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Installs dependencies
        run: npm install

      - name: Run Linter
        run: npm run eslint

      - name: Run build
        run: npm run build

      - name: Run unit tests
        run: npm run test
